// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: games.proto

package grpc_examples

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genre int32

const (
	Genre_ACTION     Genre = 0
	Genre_ADVENTURE  Genre = 1
	Genre_RPG        Genre = 2
	Genre_SHOOTER    Genre = 3
	Genre_SIMULATION Genre = 4
	Genre_STRATEGY   Genre = 5
)

// Enum value maps for Genre.
var (
	Genre_name = map[int32]string{
		0: "ACTION",
		1: "ADVENTURE",
		2: "RPG",
		3: "SHOOTER",
		4: "SIMULATION",
		5: "STRATEGY",
	}
	Genre_value = map[string]int32{
		"ACTION":     0,
		"ADVENTURE":  1,
		"RPG":        2,
		"SHOOTER":    3,
		"SIMULATION": 4,
		"STRATEGY":   5,
	}
)

func (x Genre) Enum() *Genre {
	p := new(Genre)
	*p = x
	return p
}

func (x Genre) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Genre) Descriptor() protoreflect.EnumDescriptor {
	return file_games_proto_enumTypes[0].Descriptor()
}

func (Genre) Type() protoreflect.EnumType {
	return &file_games_proto_enumTypes[0]
}

func (x Genre) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Genre.Descriptor instead.
func (Genre) EnumDescriptor() ([]byte, []int) {
	return file_games_proto_rawDescGZIP(), []int{0}
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ReleaseYear string `protobuf:"bytes,4,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	Genre       Genre  `protobuf:"varint,5,opt,name=genre,proto3,enum=grpcgames.Genre" json:"genre,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_games_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_games_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_games_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Game) GetReleaseYear() string {
	if x != nil {
		return x.ReleaseYear
	}
	return ""
}

func (x *Game) GetGenre() Genre {
	if x != nil {
		return x.Genre
	}
	return Genre_ACTION
}

var File_games_proto protoreflect.FileDescriptor

var file_games_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67,
	0x72, 0x70, 0x63, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x04, 0x47, 0x61, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x59, 0x65, 0x61, 0x72, 0x12, 0x26, 0x0a, 0x05, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x05, 0x67, 0x65, 0x6e,
	0x72, 0x65, 0x2a, 0x56, 0x0a, 0x05, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x41,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x44, 0x56, 0x45, 0x4e,
	0x54, 0x55, 0x52, 0x45, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x50, 0x47, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x48, 0x4f, 0x4f, 0x54, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a,
	0x53, 0x49, 0x4d, 0x55, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08,
	0x53, 0x54, 0x52, 0x41, 0x54, 0x45, 0x47, 0x59, 0x10, 0x05, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x68, 0x6f, 0x6d, 0x61, 0x73, 0x4c,
	0x61, 0x50, 0x69, 0x61, 0x6e, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_games_proto_rawDescOnce sync.Once
	file_games_proto_rawDescData = file_games_proto_rawDesc
)

func file_games_proto_rawDescGZIP() []byte {
	file_games_proto_rawDescOnce.Do(func() {
		file_games_proto_rawDescData = protoimpl.X.CompressGZIP(file_games_proto_rawDescData)
	})
	return file_games_proto_rawDescData
}

var file_games_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_games_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_games_proto_goTypes = []any{
	(Genre)(0),   // 0: grpcgames.Genre
	(*Game)(nil), // 1: grpcgames.Game
}
var file_games_proto_depIdxs = []int32{
	0, // 0: grpcgames.Game.genre:type_name -> grpcgames.Genre
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_games_proto_init() }
func file_games_proto_init() {
	if File_games_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_games_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_games_proto_goTypes,
		DependencyIndexes: file_games_proto_depIdxs,
		EnumInfos:         file_games_proto_enumTypes,
		MessageInfos:      file_games_proto_msgTypes,
	}.Build()
	File_games_proto = out.File
	file_games_proto_rawDesc = nil
	file_games_proto_goTypes = nil
	file_games_proto_depIdxs = nil
}
